### ISSUE TITLE
Console Code generation broken

### ISSUE THREAD

**Issue by Mrnikbobjeff** [kentcb/PCLMock#32]
When trying to use the console runner as a pre build event the resulting mocks.g.cs file can not resolve all types, as it omits the global:: keyword. Furthermore it also sometimes omits generic types in Tasks. When using the t4 template it works perfectly.

**Comment by kentcb** [comment]
I suspect this is related to #31. Will check back in once that is resolved.

**Comment by pellet** [comment]
I had the same problems, I have fixed these issues on my own fork.
I had trouble with buildalyzer so stuck to using .net targets with msbuild and things are working ok again for immultablelists and rx types.
The mock generator wouldn't recognize other 3rd party types so I just made my own plugin to add them to the compilation for the mock generator to recognize them ok.
I guess the problem might have arisen due to using .netstandard projects instead of pcl projects?
